# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build Firmware

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ARM Toolchain
        run: |
          sudo apt update
          sudo apt install -y gcc-arm-none-eabi binutils-arm-none-eabi cmake ninja-build

      - name: Configure CMake
        run: cmake -B build -G Ninja

      - name: Build project
        run: cmake --build build

      - name: Firmware info
        run: arm-none-eabi-size build/*.elf
